# Generated by Django 3.2.6 on 2021-08-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.CharField(default='No Data', max_length=255),
            preserve_default=False,
        ),
    ]
